create table sensor(
                       id int generated by default as identity primary key,
                       name varchar(100) unique not null
);

create table measurement(
                            id int generated by default as identity primary key ,
                            value double precision not null,
                            raining boolean not null,
                            measurement_time timestamp not null,
                            sensor varchar(100) references sensor(name)
);